# Generated by Django 5.1.2 on 2024-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
